import java.util.*;

class Main {
  public static void main(String[] args) {	  
		  
    Scanner input = new Scanner(System.in);
     System.out.println();
   
    System.out.println();
    System.out.println("Please enter a number between 1-70.");
      int adj = input.nextInt();
    System.out.println("Again, any number between 1-70.");
      int ver = input.nextInt();
    System.out.println("Stay with me... a final number between 1-70.");
      int nou = input.nextInt();
    
    Map<Integer, String> adjectives = new HashMap<>();

    adjectives.put(1, "Euphoric");
    adjectives.put(2, "Grim");
    adjectives.put(3, "Mystical");
    adjectives.put(4, "Gleaming");
    adjectives.put(5, "Dreary");
    adjectives.put(6, "Vibrant");
    adjectives.put(7, "Morose");
    adjectives.put(8, "Enchanting");
    adjectives.put(9, "Gaudy");
    adjectives.put(10, "Luminous");
    adjectives.put(11, "Obnoxious");
    adjectives.put(12, "Dreamy");
    adjectives.put(13, "Surreal");
    adjectives.put(14, "Tacky");
    adjectives.put(15, "Dynamic");
    adjectives.put(16, "Melancholic");
    adjectives.put(17, "Fierce");
    adjectives.put(18, "Boring");
    adjectives.put(19, "Hypnotic");
    adjectives.put(20, "Dull");
    adjectives.put(21, "Majestic");
    adjectives.put(22, "Stale");
    adjectives.put(23, "Transcendent");
    adjectives.put(24, "Lackluster");
    adjectives.put(25, "Enigmatic");
    adjectives.put(26, "Elegant");
    adjectives.put(27, "Trite");
    adjectives.put(28, "Captivating");
    adjectives.put(29, "Unremarkable");
    adjectives.put(30, "Mysterious");
    adjectives.put(31, "Deplorable");
    adjectives.put(32, "Sensational");
    adjectives.put(33, "Fascinating");
    adjectives.put(34, "Ridiculous");
    adjectives.put(35, "Intriguing");
    adjectives.put(36, "Adorable");
    adjectives.put(37, "Angry");
    adjectives.put(38, "Average");
    adjectives.put(39, "Beautiful");
    adjectives.put(40, "Bad");
    adjectives.put(41, "Bewildered");
    adjectives.put(42, "Blue-eyed");
    adjectives.put(43, "Bored");
    adjectives.put(44, "Dangerous");
    adjectives.put(45, "Kooky");
    adjectives.put(46, "Lanky");
    adjectives.put(47, "Mediocre");
    adjectives.put(48, "Quirky");
    adjectives.put(49, "Tattered");
    adjectives.put(50, "Weathered");
    adjectives.put(51, "Thorny");
    adjectives.put(52, "Precious");
    adjectives.put(53, "Miserable");
    adjectives.put(54, "Rustic");
    adjectives.put(55, "Acrobatic");
    adjectives.put(56, "Brave");
    adjectives.put(57, "Zany");
    adjectives.put(58, "Handsome");
    adjectives.put(59, "Limp");
    adjectives.put(60, "Absurd");
    adjectives.put(61, "Brazen");
    adjectives.put(62, "Deranged");
    adjectives.put(63, "Eccentric");
    adjectives.put(64, "Feral");
    adjectives.put(65, "Ferocious");
    adjectives.put(66, "Foolish");
    adjectives.put(67, "Depressed");
    adjectives.put(68, "Maniacal");
    adjectives.put(69, "Naughty");
    adjectives.put(70, "Bloody");


    Map<Integer, String> verbs = new HashMap<>();

    verbs.put(1, "pistol-whipping");
    verbs.put(2, "soul-crushing");
    verbs.put(3, "juggling");
    verbs.put(4, "smiling");
    verbs.put(5, "snuggling");
    verbs.put(6, "tripping");
    verbs.put(7, "melting");
    verbs.put(8, "eating");
    verbs.put(9, "painting");
    verbs.put(10, "exploding");
    verbs.put(11, "shrinking");
    verbs.put(12, "rotting");
    verbs.put(13, "sneaking");
    verbs.put(14, "squashing");
    verbs.put(15, "peeking");
    verbs.put(16, "fleeing");
    verbs.put(17, "creeping");
    verbs.put(18, "decaying");
    verbs.put(19, "bleeding");
    verbs.put(20, "blushing");
    verbs.put(21, "sleeping");
    verbs.put(22, "yawning");
    verbs.put(23, "winking");
    verbs.put(24, "smirking");
    verbs.put(25, "frowning");
    verbs.put(26, "glaring");
    verbs.put(27, "fighting");
    verbs.put(28, "wrestling");
    verbs.put(29, "knitting");
    verbs.put(30, "scrapbooking");
    verbs.put(31, "exercising");
    verbs.put(32, "weight-lifting");
    verbs.put(33, "flying");
    verbs.put(34, "falling");
    verbs.put(35, "over-thinking");
    verbs.put(36, "giggling");
    verbs.put(37, "whistling");
    verbs.put(38, "dancing");
    verbs.put(39, "singing");
    verbs.put(40, "laughing");
    verbs.put(41, "crying");
    verbs.put(42, "screaming");
    verbs.put(43, "sneezing");
    verbs.put(44, "hugging");
    verbs.put(45, "kissing");
    verbs.put(46, "biting");
    verbs.put(47, "scratching");
    verbs.put(48, "licking");
    verbs.put(49, "stabbing");
    verbs.put(50, "punching");
    verbs.put(51, "slapping");
    verbs.put(52, "smacking");
    verbs.put(53, "shoving");
    verbs.put(54, "throwing");
    verbs.put(55, "catching");
    verbs.put(56, "shooting");
    verbs.put(57, "blasting");
    verbs.put(58, "boiling");
    verbs.put(59, "baking");
    verbs.put(60, "chopping");
    verbs.put(61, "grilling");
    verbs.put(62, "stirring");
    verbs.put(63, "stomping");
    verbs.put(64, "dunking");
    verbs.put(65, "dipping");
    verbs.put(66, "diving");
    verbs.put(67, "flipping");
    verbs.put(68, "hurdling");
    verbs.put(69, "vaulting");
    verbs.put(70, "gliding");

    Map<Integer, String> nouns = new HashMap<>();

    nouns.put(1, "nurse");
    nouns.put(2, "fireman");
    nouns.put(3, "teacher");
    nouns.put(4, "koi fish");
    nouns.put(5, "emo girl");
    nouns.put(6, "policeman");
    nouns.put(7, "toddler");
    nouns.put(8, "librarian");
    nouns.put(9, "unicorn");
    nouns.put(10, "badger");
    nouns.put(11, "anaconda");
    nouns.put(12, "tiger shark");
    nouns.put(13, "pterodactyl");
    nouns.put(14, "moose");
    nouns.put(15, "koala");
    nouns.put(16, "tarantula");
    nouns.put(17, "old man");
    nouns.put(18, "grandma");
    nouns.put(19, "mailman");
    nouns.put(20, "waitress");
    nouns.put(21, "house plant");
    nouns.put(22, "bald eagle");
    nouns.put(23, "pitbull");
    nouns.put(24, "chihuahua");
    nouns.put(25, "barbie");
    nouns.put(26, "mean girl");
    nouns.put(27, "bratz doll");
    nouns.put(28, "GI Joe");
    nouns.put(29, "shrimp cocktail");
    nouns.put(30, "zombie");
    nouns.put(31, "vampire");
    nouns.put(32, "soldier");
    nouns.put(33, "witch");
    nouns.put(34, "super hero");
    nouns.put(35, "dinosaur");
    nouns.put(36, "pianist");
    nouns.put(37, "chef");
    nouns.put(38, "astronaut");
    nouns.put(39, "cupcake");
    nouns.put(40, "skateboarder");
    nouns.put(41, "snorkler");
    nouns.put(42, "banana");
    nouns.put(43, "hiker");
    nouns.put(44, "juggler");
    nouns.put(45, "magician");
    nouns.put(46, "swimmer");
    nouns.put(47, "guitarist");
    nouns.put(48, "pilot");
    nouns.put(49, "waiter");
    nouns.put(50, "dancer");
    nouns.put(51, "boxer");
    nouns.put(52, "barista");
    nouns.put(53, "geologist");
    nouns.put(54, "biologist");
    nouns.put(55, "historian");
    nouns.put(56, "artist");
    nouns.put(57, "sailor");
    nouns.put(58, "climber");
    nouns.put(59, "surfer");
    nouns.put(60, "skier");
    nouns.put(61, "snowboarder");
    nouns.put(62, "swimmer");
    nouns.put(63, "pirate");
    nouns.put(64, "race car driver");
    nouns.put(65, "mechanic");
    nouns.put(66, "zookeeper");
    nouns.put(67, "astronomer");
    nouns.put(68, "archaeologist");
    nouns.put(69, "meteorologist");
    nouns.put(70, "comedian");


  System.out.println("Your random tattoo idea is a " + adjectives.get(adj)+ " " + verbs.get(ver) + " " + nouns.get(nou) + ".");
 
  }
}